### ISSUE TITLE
Not working with replicaset, also slaveOk

### ISSUE THREAD

**Issue by stephanustedy** [james75/SolrMongoImporter#11]
Not working with replicaset, also slaveOk

**Comment by kgcrom** [comment]
Do you get a error?
```
2016-04-26 02:19:47.487 ERROR (Thread-21) [   x:sprinklr] o.a.s.h.d.DataImporter Full Import failed:java.lang.RuntimeException: java.lang.RuntimeException: org.apache.solr.handler.dataimport.DataImportHandlerException: com.mongodb.MongoException: not talking to master and retries used up
	at org.apache.solr.handler.dataimport.DocBuilder.execute(DocBuilder.java:270)
	at org.apache.solr.handler.dataimport.DataImporter.doFullImport(DataImporter.java:416)
	at org.apache.solr.handler.dataimport.DataImporter.runCmd(DataImporter.java:480)
	at org.apache.solr.handler.dataimport.DataImporter$1.run(DataImporter.java:461)
Caused by: java.lang.RuntimeException: org.apache.solr.handler.dataimport.DataImportHandlerException: com.mongodb.MongoException: not talking to master and retries used up
	at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:416)
	at org.apache.solr.handler.dataimport.DocBuilder.doFullDump(DocBuilder.java:329)
	at org.apache.solr.handler.dataimport.DocBuilder.execute(DocBuilder.java:232)
	... 3 more
Caused by: org.apache.solr.handler.dataimport.DataImportHandlerException: com.mongodb.MongoException: not talking to master and retries used up
	at org.apache.solr.handler.dataimport.DataImportHandlerException.wrapAndThrow(DataImportHandlerException.java:61)
	at org.apache.solr.handler.dataimport.MongoDataSource$ResultSetIterator.hasnext(MongoDataSource.java:144)
	at org.apache.solr.handler.dataimport.MongoDataSource$ResultSetIterator.access$000(MongoDataSource.java:85)
	at org.apache.solr.handler.dataimport.MongoDataSource$ResultSetIterator$1.hasNext(MongoDataSource.java:96)
	at org.apache.solr.handler.dataimport.EntityProcessorBase.getNext(EntityProcessorBase.java:133)
	at org.apache.solr.handler.dataimport.MongoEntityProcessor.nextRow(MongoEntityProcessor.java:56)
	at org.apache.solr.handler.dataimport.EntityProcessorWrapper.nextRow(EntityProcessorWrapper.java:244)
	at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:475)
	at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:414)
	... 5 more
Caused by: com.mongodb.MongoException: not talking to master and retries used up
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:314)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:316)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:316)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:257)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:310)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:295)
	at com.mongodb.DBCursor._check(DBCursor.java:368)
	at com.mongodb.DBCursor._hasNext(DBCursor.java:459)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:484)
	at org.apache.solr.handler.dataimport.MongoDataSource$ResultSetIterator.hasnext(MongoDataSource.java:136)
	... 12 more
```

and
What is your MongoDB version?
If you are using 3.0 < , neeed to upgrade mongodb-java-driver and refactor code.
I am testing... 😢
