### ISSUE TITLE
couldn't data import from remote mongo cluster

### ISSUE THREAD

**Issue by sarankani** [james75/SolrMongoImporter#23]
I tried to connect my remote mongo server and i gave inbound rules permission for 27017

I couldn't import data from my mongo cluster.

I checked my primary db server i got this following error.
2018-11-20 06:08:32.915 INFO  (Thread-27) [   x:businesses] o.m.d.connection Closed connection [connectionId{localValue:136, serverValue:72}] to xx.xxx.xx.xxx:27017 because the pool has been closed.

My data-config.xml
`<dataConfig>
  <dataSource name="MongoSource" type="MongoDataSource" host="xx.xxx.xx.xxx" database="mydbname" username="xxxxxx" password="xxxxxx" />
    <document name="import">
      <entity processor="MongoEntityProcessor"
             datasource="MongoSource"
             transformer="MongoMapperTransformer"
             collection="users"
             name="users"
             query="">
            <field column="_id" name="_id" mongoField="_id" />
            <field column="id" name="id" mongoField="_id" />
            <field column="name" name="j_name" mongoField="name" />
............`

is there any option to use mongo connection uri like mongodb://localhost1:27017,localhost2:27017,localhost3:27017/mydbname?readPreference=nearest&replicaSet=rs01

Please anybody help me. Thanks in advance.

**Comment by vb1704** [comment]
Having same issue.

It gives error on MongoDataSource.java file line no 57.
java.lang.NoSuchMethodError: com.mongodb.DB.authenticate(Ljava/lang/String;[C)Z
	at org.apache.solr.handler.dataimport.MongoDataSource.init(MongoDataSource.java:57)

Can anyone help?

**Comment by Lambosss** [comment]
> Having same issue.
> 
> It gives error on MongoDataSource.java file line no 57.
> java.lang.NoSuchMethodError: com.mongodb.DB.authenticate(Ljava/lang/String;[C)Z
> at org.apache.solr.handler.dataimport.MongoDataSource.init(MongoDataSource.java:57)
> 
> Can anyone help?

I know this is old, but the method authenticate was deprecated.
http://api.mongodb.com/java/2.12/com/mongodb/DB.html#authenticate(java.lang.String,%20char[])

You're supposed to use  MongoClient.MongoClient(java.util.List, java.util.List).
http://api.mongodb.com/java/2.12/com/mongodb/MongoClient.html#MongoClient(java.util.List,%20java.util.List)
